# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

pod 'AdGeneration'
pod 'FBAudienceNetwork', '~> 4.24.0'

target 'BannerAdsObjC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BannerAdsObjC

end

target 'BannerAdsSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BannerAdsSwift

end

target 'InterstitialAdsObjC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InterstitialAdsObjC

end

target 'InterstitialAdsSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for InterstitialAdsSwift

end

target 'NativeAdsObjC' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativeAdsObjC

end

target 'NativeAdsSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NativeAdsSwift

end
